[package]
name = "reprise-p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
log = "0.4.29"
parking_lot = "0.12.5"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "net", "macros", "sync", "time"] }
if-addrs = "0.15.0"
multicast-discovery-socket = "0.1.3"
rand = "0.10.1"
reprise-net-util = {git = "https://github.com/Reprise-Rust/reprise-net-util.git"}

ctrlc = "3.5.2"
thiserror = "2.0.18"
ed25519-dalek = { version = "3.0.0-rc.0", features = ["rand_core", "pkcs8", "alloc"] }
chrono = "0.4.44"
socket2 = "0.6.4"
anyhow = "1.0.102"
quinn = "0.11.9"
rcgen = "0.14.8"
x509-parser = "0.18.1"
reqwest = "0.13.4"

[dev-dependencies]
simple_logger = "5.2.0"
base64 = "0.22.1"
